
export const projects = [
    {
      id: 1,
      title: "Project One",
      description: "A modern web application built with Next.js and TypeScript",
      image: "/a7.jpg",
      category: "Web Development",
      slug: "project-one",
    },
    {
      id: 2,
      title: "Project Two",
      description: "Full-stack application with real-time features",
      image: "/a7.jpg",
      category: "Full Stack",
      slug: "project-two",
    },
    {
      id: 3,
      title: "Project Three",
      description: "Mobile-first responsive design implementation",
      image: "/a7.jpg",
      category: "UI/UX Design",
      slug: "project-three",
    },
    {
      id: 4,
      title: "Project Four",
      description: "E-commerce platform with advanced features",
      image: "/a7.jpg",
      category: "E-commerce",
      slug: "project-four",
    },
    {
      id: 5,
      title: "Project Five",
      description: "Content management system with modern architecture",
      image: "/a7.jpg",
      category: "CMS",
      slug: "project-five",
    },
    {
      id: 6,
      title: "Project Six",
      description: "Social media platform with real-time messaging",
      image: "/a7.jpg",
      category: "Social Media",
      slug: "project-six",
    },
  ];
